server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/mabitdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create # create, update, none
      show_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl